In [1]:
import pandas as pd

In [2]:
temp_1 = "data/all_players_cleaned.csv"
hist   = "data/historical_players_raw.csv"

In [3]:
team = "Real Madrid"

In [127]:
df1 = pd.read_csv(temp_1)
df2 = pd.read_csv(hist)

In [128]:
df1["Season"] = "2024-25"

In [129]:
df2.drop("matches", axis=1, inplace=True)

In [130]:
df2 = df2[df1.columns]

In [131]:
df1.shape, df2.shape

((18590, 192), (13265, 192))

In [132]:
df1.head(1)

,player,nationality,position,age,games,games_starts,minutes,minutes_90s,goals,assists,...,plus_minus_wow,on_xg_for,on_xg_against,xg_plus_minus,xg_plus_minus_per90,xg_plus_minus_wow,Team,League,Team_Logo,Season
0,Pedri,ESP,MF,21,37,35,"2,879",32.0,4.0,5.0,...,-1.19,70.8,34.6,36.2,1.13,-1.09,Barcelona,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/2...,2024-25

In [133]:
df2.head(1)

,player,nationality,position,age,games,games_starts,minutes,minutes_90s,goals,assists,...,plus_minus_wow,on_xg_for,on_xg_against,xg_plus_minus,xg_plus_minus_per90,xg_plus_minus_wow,Team,League,Team_Logo,Season
0,Ederson,BRA,GK,26.0,36,36,"3,240",36.0,0.0,1.0,...,-0.17,64.1,27.2,36.9,1.03,0.49,Manchester City,Premier League,https://cdn.ssref.net/req/202509241/tlogo/fb/b...,2020-21

In [134]:
df_final = pd.concat([df1, df2], axis=0)

In [135]:
df_final.shape

(31855, 192)

In [136]:
df2.player.nunique(), df1.player.nunique()

(6262, 16827)

In [139]:
len(set(df1.player.unique()).difference(set(df2.player.unique())))

12922

In [140]:
df_final["minutes"] = df_final["minutes"].fillna("0")
df_final["minutes.1"] = df_final["minutes.1"].fillna("0")

In [141]:
df_final["minutes"] = df_final["minutes"].apply(lambda x: float(x.replace(",","")))
df_final["minutes.1"] = df_final["minutes.1"].apply(lambda x: float(str(x).replace(",",".")))

In [142]:
df_final["minutes.1"].describe()

count    31855.000000
mean       158.876301
std        269.368740
min          0.000000
25%          1.292000
50%          2.609000
75%        215.000000
max        999.000000
Name: minutes.1, dtype: float64

In [143]:
df_final.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 31855 entries, 0 to 13264
Data columns (total 192 columns):
 #    Column                                 Non-Null Count  Dtype
---   ------                                 --------------  -----
 0    player                                 31855 non-null  object
 1    nationality                            31840 non-null  object
 2    position                               31853 non-null  object
 3    age                                    31849 non-null  float64
 4    games                                  31855 non-null  int64
 5    games_starts                           31855 non-null  int64
 6    minutes                                31855 non-null  float64
 7    minutes_90s                            29459 non-null  float64
 8    goals                                  29459 non-null  float64
 9    assists                                29459 non-null  float64
 10   goals_assists                          29459 non-null  float64
 11   goals_pens                             29459 non-null  float64
 12   pens_made                              29459 non-null  float64
 13   pens_att                               29459 non-null  float64
 14   cards_yellow                           29459 non-null  float64
 15   cards_red                              29459 non-null  float64
 16   xg                                     29443 non-null  float64
 17   npxg                                   29443 non-null  float64
 18   xg_assist                              29443 non-null  float64
 19   npxg_xg_assist                         29443 non-null  float64
 20   progressive_carries                    29443 non-null  float64
 21   progressive_passes                     29443 non-null  float64
 22   progressive_passes_received            29443 non-null  float64
 23   goals_per90                            29443 non-null  float64
 24   assists_per90                          29443 non-null  float64
 25   goals_assists_per90                    29443 non-null  float64
 26   goals_pens_per90                       29443 non-null  float64
 27   goals_assists_pens_per90               29443 non-null  float64
 28   xg_per90                               29443 non-null  float64
 29   xg_assist_per90                        29443 non-null  float64
 30   xg_xg_assist_per90                     29443 non-null  float64
 31   npxg_per90                             29443 non-null  float64
 32   npxg_xg_assist_per90                   29443 non-null  float64
 33   gk_goals_against                       19376 non-null  float64
 34   gk_pens_allowed                        19376 non-null  float64
 35   gk_free_kick_goals_against             19376 non-null  float64
 36   gk_corner_kick_goals_against           19376 non-null  float64
 37   gk_own_goals_against                   19376 non-null  float64
 38   gk_psxg                                19377 non-null  float64
 39   gk_psnpxg_per_shot_on_target_against   19365 non-null  float64
 40   gk_psxg_net                            19376 non-null  float64
 41   gk_psxg_net_per90                      19376 non-null  float64
 42   gk_passes_completed_launched           19378 non-null  float64
 43   gk_passes_launched                     19378 non-null  float64
 44   gk_passes_pct_launched                 19369 non-null  float64
 45   gk_passes                              19377 non-null  float64
 46   gk_passes_throws                       19378 non-null  float64
 47   gk_pct_passes_launched                 19377 non-null  float64
 48   gk_passes_length_avg                   19377 non-null  float64
 49   gk_goal_kicks                          19377 non-null  float64
 50   gk_pct_goal_kicks_launched             19369 non-null  float64
 51   gk_goal_kick_length_avg                19369 non-null  float64
 52   gk_crosses                             19377 non-null  float64
 53   gk_crosses_stopped                     19377 non-null  float64
 54   gk_crosses_stopped_pct                 19371 non-null  float64
 55   gk_def_actions_outside_pen_area        19376 non-null  float64
 56   gk_def_actions_outside_pen_area_per90  19376 non-null  float64
 57   gk_avg_distance_def_actions            19358 non-null  float64
 58   goals.1                                29443 non-null  float64
 59   shots                                  29443 non-null  float64
 60   shots_on_target                        29443 non-null  float64
 61   shots_on_target_pct                    27409 non-null  float64
 62   shots_per90                            29443 non-null  float64
 63   shots_on_target_per90                  29443 non-null  float64
 64   goals_per_shot                         27409 non-null  float64
 65   goals_per_shot_on_target               26068 non-null  float64
 66   average_shot_distance                  27407 non-null  float64
 67   shots_free_kicks                       29443 non-null  float64
 68   pens_made.1                            29443 non-null  float64
 69   pens_att.1                             29443 non-null  float64
 70   xg.1                                   29443 non-null  float64
 71   npxg.1                                 29443 non-null  float64
 72   npxg_per_shot                          27407 non-null  float64
 73   xg_net                                 29443 non-null  float64
 74   npxg_net                               29443 non-null  float64
 75   passes_completed                       29443 non-null  float64
 76   passes                                 29443 non-null  float64
 77   passes_pct                             29365 non-null  float64
 78   passes_total_distance                  29443 non-null  float64
 79   passes_progressive_distance            29443 non-null  float64
 80   passes_completed_short                 29443 non-null  float64
 81   passes_short                           29443 non-null  float64
 82   passes_pct_short                       29269 non-null  float64
 83   passes_completed_medium                29443 non-null  float64
 84   passes_medium                          29443 non-null  float64
 85   passes_pct_medium                      29146 non-null  float64
 86   passes_completed_long                  29443 non-null  float64
 87   passes_long                            29443 non-null  float64
 88   passes_pct_long                        28742 non-null  float64
 89   assists.1                              29443 non-null  float64
 90   xg_assist.1                            29443 non-null  float64
 91   pass_xa                                29443 non-null  float64
 92   xg_assist_net                          29443 non-null  float64
 93   assisted_shots                         29443 non-null  float64
 94   passes_into_final_third                29443 non-null  float64
 95   passes_into_penalty_area               29443 non-null  float64
 96   crosses_into_penalty_area              29443 non-null  float64
 97   progressive_passes.1                   29443 non-null  float64
 98   passes.1                               29443 non-null  float64
 99   passes_live                            29443 non-null  float64
 100  passes_dead                            29443 non-null  float64
 101  passes_free_kicks                      29443 non-null  float64
 102  through_balls                          29443 non-null  float64
 103  passes_switches                        29443 non-null  float64
 104  crosses                                29443 non-null  float64
 105  throw_ins                              29443 non-null  float64
 106  corner_kicks                           29443 non-null  float64
 107  corner_kicks_in                        29443 non-null  float64
 108  corner_kicks_out                       29443 non-null  float64
 109  corner_kicks_straight                  29443 non-null  float64
 110  passes_completed.1                     29443 non-null  float64
 111  passes_offsides                        29443 non-null  float64
 112  passes_blocked                         29443 non-null  float64
 113  sca                                    29443 non-null  float64
 114  sca_per90                              29443 non-null  float64
 115  sca_passes_live                        29443 non-null  float64
 116  sca_passes_dead                        29443 non-null  float64
 117  sca_take_ons                           29443 non-null  float64
 118  sca_shots                              29443 non-null  float64
 119  sca_fouled                             29443 non-null  float64
 120  sca_defense                            29443 non-null  float64
 121  gca                                    29443 non-null  float64
 122  gca_per90                              29443 non-null  float64
 123  gca_passes_live                        29443 non-null  float64
 124  gca_passes_dead                        29443 non-null  float64
 125  gca_take_ons                           29443 non-null  float64
 126  gca_shots                              29443 non-null  float64
 127  gca_fouled                             29443 non-null  float64
 128  gca_defense                            29443 non-null  float64
 129  tackles                                29443 non-null  float64
 130  tackles_won                            29443 non-null  float64
 131  tackles_def_3rd                        29443 non-null  float64
 132  tackles_mid_3rd                        29443 non-null  float64
 133  tackles_att_3rd                        29443 non-null  float64
 134  challenge_tackles                      29443 non-null  float64
 135  challenges                             29443 non-null  float64
 136  challenge_tackles_pct                  28140 non-null  float64
 137  challenges_lost                        29443 non-null  float64
 138  blocks                                 29443 non-null  float64
 139  blocked_shots                          29443 non-null  float64
 140  blocked_passes                         29443 non-null  float64
 141  interceptions                          29443 non-null  float64
 142  tackles_interceptions                  29443 non-null  float64
 143  clearances                             29443 non-null  float64
 144  errors                                 29443 non-null  float64
 145  touches                                29443 non-null  float64
 146  touches_def_pen_area                   29443 non-null  float64
 147  touches_def_3rd                        29443 non-null  float64
 148  touches_mid_3rd                        29443 non-null  float64
 149  touches_att_3rd                        29443 non-null  float64
 150  touches_att_pen_area                   29443 non-null  float64
 151  touches_live_ball                      29443 non-null  float64
 152  take_ons                               29443 non-null  float64
 153  take_ons_won                           29443 non-null  float64
 154  take_ons_won_pct                       27721 non-null  float64
 155  take_ons_tackled                       29443 non-null  float64
 156  take_ons_tackled_pct                   27721 non-null  float64
 157  carries                                29443 non-null  float64
 158  carries_distance                       29443 non-null  float64
 159  carries_progressive_distance           29443 non-null  float64
 160  progressive_carries.1                  29443 non-null  float64
 161  carries_into_final_third               29443 non-null  float64
 162  carries_into_penalty_area              29443 non-null  float64
 163  miscontrols                            29443 non-null  float64
 164  dispossessed                           29443 non-null  float64
 165  passes_received                        29443 non-null  float64
 166  progressive_passes_received.1          29443 non-null  float64
 167  games.1                                31855 non-null  int64
 168  minutes.1                              31855 non-null  float64
 169  minutes_per_game                       29443 non-null  float64
 170  minutes_pct                            29459 non-null  float64
 171  games_starts.1                         31855 non-null  int64
 172  minutes_per_start                      27987 non-null  float64
 173  games_complete                         31624 non-null  float64
 174  games_subs                             31855 non-null  int64
 175  minutes_per_sub                        27834 non-null  float64
 176  unused_subs                            31855 non-null  int64
 177  points_per_game                        29450 non-null  float64
 178  on_goals_for                           29459 non-null  float64
 179  on_goals_against                       29459 non-null  float64
 180  plus_minus                             29459 non-null  float64
 181  plus_minus_per90                       29443 non-null  float64
 182  plus_minus_wow                         29369 non-null  float64
 183  on_xg_for                              29443 non-null  float64
 184  on_xg_against                          29443 non-null  float64
 185  xg_plus_minus                          29443 non-null  float64
 186  xg_plus_minus_per90                    29443 non-null  float64
 187  xg_plus_minus_wow                      29369 non-null  float64
 188  Team                                   31855 non-null  object
 189  League                                 31855 non-null  object
 190  Team_Logo                              31855 non-null  object
 191  Season                                 31855 non-null  object
dtypes: float64(179), int64(6), object(7)
memory usage: 46.9+ MB

In [144]:
cat_cols = ["player", "nationality", "position","age", "Team", "League", "Team_Logo", "Season"]
num_cols = ["player"] + [c for c in df_final.columns if c not in cat_cols]

In [145]:
df_cat = df_final[cat_cols]

In [146]:
df_num = df_final[num_cols]

In [147]:
 df_cat.sort_values(["player", "Season"], ascending=[False, False]).groupby("player").first()

,nationality,position,age,Team,League,Team_Logo,Season
player,,,,,,,
AJ Marcucci,USA,GK,25.0,NY Red Bulls,Major League Soccer Eastern Conf,https://cdn.ssref.net/req/202507021/tlogo/fb/6...,2024-25
ALex Salomón,ESP,MF,28.0,Botoșani,Roumanian League I,https://cdn.ssref.net/req/202507021/tlogo/fb/d...,2024-25
Aapo Halme,FIN,DF,25.0,HJK,Veikkausliiga,https://cdn.ssref.net/req/202507021/tlogo/fb/d...,2024-25
Aapo Mäenpää,FIN,DF,26.0,Ilves,Veikkausliiga,https://cdn.ssref.net/req/202507021/tlogo/fb/a...,2024-25
Aaro Toivonen,FIN,MF,18.0,HJK,Veikkausliiga,https://cdn.ssref.net/req/202507021/tlogo/fb/d...,2024-25
...,...,...,...,...,...,...,...
Ștefan Georgescu,ROU,GK,22.0,Unirea Slobozia,Roumanian League I,https://cdn.ssref.net/req/202507021/tlogo/fb/0...,2024-25
Ștefan Opriș,ROU,MF,17.0,Universitatea Cluj,Roumanian League I,https://cdn.ssref.net/req/202507021/tlogo/fb/a...,2024-25
Ștefan Radu,ROU,FW,35.0,Lazio,Serie A,https://cdn.ssref.net/req/202509241/tlogo/fb/7...,2022-23
Ștefan Teodor Farcaș,ROU,DF,21.0,Oțelul Galați,Roumanian League I,https://cdn.ssref.net/req/202507021/tlogo/fb/8...,2024-25
Ștefan Vlădoiu,ROU,DF,25.0,CS U Craiova,Roumanian League I,https://cdn.ssref.net/req/202507021/tlogo/fb/1...,2024-25

In [162]:
df_cat_agg = df_cat.sort_values(["player", "Season"], ascending=[False, False]).groupby("player").first().reset_index()

In [163]:
assert df_cat_agg.shape[0] == df_final["player"].nunique()

In [164]:
df_cat_agg.Season.value_counts()

Season
2024-25    16827
2023-24      661
2020-21      621
2022-23      584
2021-22      491
Name: count, dtype: int64

In [165]:
df_cat_agg["player_status"] = df_cat_agg["Season"].apply(lambda x: "active" if x == "2024-25" else "retired or inactive")

In [166]:
df_num[df_num.minutes == 0].shape, df_num.shape

((5279, 185), (31855, 185))

In [167]:
df_final[df_final.minutes == 0]

,player,nationality,position,age,games,games_starts,minutes,minutes_90s,goals,assists,...,plus_minus_wow,on_xg_for,on_xg_against,xg_plus_minus,xg_plus_minus_per90,xg_plus_minus_wow,Team,League,Team_Logo,Season
28,Ander Astralaga,ESP,GK,20.0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Barcelona,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/2...,2024-25
29,Álvaro Cortés,ESP,DF,19.0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Barcelona,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/2...,2024-25
30,Andres Cuenca,ESP,DF,17.0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Barcelona,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/2...,2024-25
31,Noah Darvich,GER,MF,17.0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Barcelona,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/2...,2024-25
32,Landry Farré,ESP,DF,17.0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Barcelona,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/2...,2024-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13229,Dominique Youfeigane,CTA,GK,23.0,0,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Lorient,Ligue 1,https://cdn.ssref.net/req/202509241/tlogo/fb/d...,2023-24
13261,Stan Berkani,ALG,MF,19.0,0,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Clermont Foot,Ligue 1,https://cdn.ssref.net/req/202509241/tlogo/fb/d...,2023-24
13262,Théo Borne,FRA,GK,21.0,0,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Clermont Foot,Ligue 1,https://cdn.ssref.net/req/202509241/tlogo/fb/d...,2023-24
13263,Théo Ramousse,FRA,GK,18.0,0,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Clermont Foot,Ligue 1,https://cdn.ssref.net/req/202509241/tlogo/fb/d...,2023-24
13264,Mohamed Sylla,FRA,DF,19.0,0,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Clermont Foot,Ligue 1,https://cdn.ssref.net/req/202509241/tlogo/fb/d...,2023-24

In [168]:
df_num_agg = df_num[df_num.minutes > 0].groupby("player").mean().reset_index()

In [169]:
df_num_agg.shape

(15882, 185)

In [170]:
df_final_agg = df_cat_agg.merge(df_num_agg, on = "player", how="left")

In [171]:
df_final_agg.shape

(19184, 193)

In [172]:
df_final_agg.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19184 entries, 0 to 19183
Data columns (total 193 columns):
 #    Column                                 Non-Null Count  Dtype
---   ------                                 --------------  -----
 0    player                                 19184 non-null  object
 1    nationality                            19176 non-null  object
 2    position                               19182 non-null  object
 3    age                                    19182 non-null  float64
 4    Team                                   19184 non-null  object
 5    League                                 19184 non-null  object
 6    Team_Logo                              19184 non-null  object
 7    Season                                 19184 non-null  object
 8    player_status                          19184 non-null  object
 9    games                                  15882 non-null  float64
 10   games_starts                           15882 non-null  float64
 11   minutes                                15882 non-null  float64
 12   minutes_90s                            15882 non-null  float64
 13   goals                                  15882 non-null  float64
 14   assists                                15882 non-null  float64
 15   goals_assists                          15882 non-null  float64
 16   goals_pens                             15882 non-null  float64
 17   pens_made                              15882 non-null  float64
 18   pens_att                               15882 non-null  float64
 19   cards_yellow                           15882 non-null  float64
 20   cards_red                              15882 non-null  float64
 21   xg                                     15882 non-null  float64
 22   npxg                                   15882 non-null  float64
 23   xg_assist                              15882 non-null  float64
 24   npxg_xg_assist                         15882 non-null  float64
 25   progressive_carries                    15882 non-null  float64
 26   progressive_passes                     15882 non-null  float64
 27   progressive_passes_received            15882 non-null  float64
 28   goals_per90                            15882 non-null  float64
 29   assists_per90                          15882 non-null  float64
 30   goals_assists_per90                    15882 non-null  float64
 31   goals_pens_per90                       15882 non-null  float64
 32   goals_assists_pens_per90               15882 non-null  float64
 33   xg_per90                               15882 non-null  float64
 34   xg_assist_per90                        15882 non-null  float64
 35   xg_xg_assist_per90                     15882 non-null  float64
 36   npxg_per90                             15882 non-null  float64
 37   npxg_xg_assist_per90                   15882 non-null  float64
 38   gk_goals_against                       14454 non-null  float64
 39   gk_pens_allowed                        14454 non-null  float64
 40   gk_free_kick_goals_against             14454 non-null  float64
 41   gk_corner_kick_goals_against           14454 non-null  float64
 42   gk_own_goals_against                   14454 non-null  float64
 43   gk_psxg                                14454 non-null  float64
 44   gk_psnpxg_per_shot_on_target_against   14449 non-null  float64
 45   gk_psxg_net                            14454 non-null  float64
 46   gk_psxg_net_per90                      14454 non-null  float64
 47   gk_passes_completed_launched           14454 non-null  float64
 48   gk_passes_launched                     14454 non-null  float64
 49   gk_passes_pct_launched                 14451 non-null  float64
 50   gk_passes                              14454 non-null  float64
 51   gk_passes_throws                       14454 non-null  float64
 52   gk_pct_passes_launched                 14454 non-null  float64
 53   gk_passes_length_avg                   14454 non-null  float64
 54   gk_goal_kicks                          14454 non-null  float64
 55   gk_pct_goal_kicks_launched             14449 non-null  float64
 56   gk_goal_kick_length_avg                14449 non-null  float64
 57   gk_crosses                             14454 non-null  float64
 58   gk_crosses_stopped                     14454 non-null  float64
 59   gk_crosses_stopped_pct                 14449 non-null  float64
 60   gk_def_actions_outside_pen_area        14454 non-null  float64
 61   gk_def_actions_outside_pen_area_per90  14454 non-null  float64
 62   gk_avg_distance_def_actions            14444 non-null  float64
 63   goals.1                                15882 non-null  float64
 64   shots                                  15882 non-null  float64
 65   shots_on_target                        15882 non-null  float64
 66   shots_on_target_pct                    15394 non-null  float64
 67   shots_per90                            15882 non-null  float64
 68   shots_on_target_per90                  15882 non-null  float64
 69   goals_per_shot                         15394 non-null  float64
 70   goals_per_shot_on_target               15152 non-null  float64
 71   average_shot_distance                  15393 non-null  float64
 72   shots_free_kicks                       15882 non-null  float64
 73   pens_made.1                            15882 non-null  float64
 74   pens_att.1                             15882 non-null  float64
 75   xg.1                                   15882 non-null  float64
 76   npxg.1                                 15882 non-null  float64
 77   npxg_per_shot                          15393 non-null  float64
 78   xg_net                                 15882 non-null  float64
 79   npxg_net                               15882 non-null  float64
 80   passes_completed                       15882 non-null  float64
 81   passes                                 15882 non-null  float64
 82   passes_pct                             15850 non-null  float64
 83   passes_total_distance                  15882 non-null  float64
 84   passes_progressive_distance            15882 non-null  float64
 85   passes_completed_short                 15882 non-null  float64
 86   passes_short                           15882 non-null  float64
 87   passes_pct_short                       15823 non-null  float64
 88   passes_completed_medium                15882 non-null  float64
 89   passes_medium                          15882 non-null  float64
 90   passes_pct_medium                      15775 non-null  float64
 91   passes_completed_long                  15882 non-null  float64
 92   passes_long                            15882 non-null  float64
 93   passes_pct_long                        15658 non-null  float64
 94   assists.1                              15882 non-null  float64
 95   xg_assist.1                            15882 non-null  float64
 96   pass_xa                                15882 non-null  float64
 97   xg_assist_net                          15882 non-null  float64
 98   assisted_shots                         15882 non-null  float64
 99   passes_into_final_third                15882 non-null  float64
 100  passes_into_penalty_area               15882 non-null  float64
 101  crosses_into_penalty_area              15882 non-null  float64
 102  progressive_passes.1                   15882 non-null  float64
 103  passes.1                               15882 non-null  float64
 104  passes_live                            15882 non-null  float64
 105  passes_dead                            15882 non-null  float64
 106  passes_free_kicks                      15882 non-null  float64
 107  through_balls                          15882 non-null  float64
 108  passes_switches                        15882 non-null  float64
 109  crosses                                15882 non-null  float64
 110  throw_ins                              15882 non-null  float64
 111  corner_kicks                           15882 non-null  float64
 112  corner_kicks_in                        15882 non-null  float64
 113  corner_kicks_out                       15882 non-null  float64
 114  corner_kicks_straight                  15882 non-null  float64
 115  passes_completed.1                     15882 non-null  float64
 116  passes_offsides                        15882 non-null  float64
 117  passes_blocked                         15882 non-null  float64
 118  sca                                    15882 non-null  float64
 119  sca_per90                              15882 non-null  float64
 120  sca_passes_live                        15882 non-null  float64
 121  sca_passes_dead                        15882 non-null  float64
 122  sca_take_ons                           15882 non-null  float64
 123  sca_shots                              15882 non-null  float64
 124  sca_fouled                             15882 non-null  float64
 125  sca_defense                            15882 non-null  float64
 126  gca                                    15882 non-null  float64
 127  gca_per90                              15882 non-null  float64
 128  gca_passes_live                        15882 non-null  float64
 129  gca_passes_dead                        15882 non-null  float64
 130  gca_take_ons                           15882 non-null  float64
 131  gca_shots                              15882 non-null  float64
 132  gca_fouled                             15882 non-null  float64
 133  gca_defense                            15882 non-null  float64
 134  tackles                                15882 non-null  float64
 135  tackles_won                            15882 non-null  float64
 136  tackles_def_3rd                        15882 non-null  float64
 137  tackles_mid_3rd                        15882 non-null  float64
 138  tackles_att_3rd                        15882 non-null  float64
 139  challenge_tackles                      15882 non-null  float64
 140  challenges                             15882 non-null  float64
 141  challenge_tackles_pct                  15545 non-null  float64
 142  challenges_lost                        15882 non-null  float64
 143  blocks                                 15882 non-null  float64
 144  blocked_shots                          15882 non-null  float64
 145  blocked_passes                         15882 non-null  float64
 146  interceptions                          15882 non-null  float64
 147  tackles_interceptions                  15882 non-null  float64
 148  clearances                             15882 non-null  float64
 149  errors                                 15882 non-null  float64
 150  touches                                15882 non-null  float64
 151  touches_def_pen_area                   15882 non-null  float64
 152  touches_def_3rd                        15882 non-null  float64
 153  touches_mid_3rd                        15882 non-null  float64
 154  touches_att_3rd                        15882 non-null  float64
 155  touches_att_pen_area                   15882 non-null  float64
 156  touches_live_ball                      15882 non-null  float64
 157  take_ons                               15882 non-null  float64
 158  take_ons_won                           15882 non-null  float64
 159  take_ons_won_pct                       15466 non-null  float64
 160  take_ons_tackled                       15882 non-null  float64
 161  take_ons_tackled_pct                   15466 non-null  float64
 162  carries                                15882 non-null  float64
 163  carries_distance                       15882 non-null  float64
 164  carries_progressive_distance           15882 non-null  float64
 165  progressive_carries.1                  15882 non-null  float64
 166  carries_into_final_third               15882 non-null  float64
 167  carries_into_penalty_area              15882 non-null  float64
 168  miscontrols                            15882 non-null  float64
 169  dispossessed                           15882 non-null  float64
 170  passes_received                        15882 non-null  float64
 171  progressive_passes_received.1          15882 non-null  float64
 172  games.1                                15882 non-null  float64
 173  minutes.1                              15882 non-null  float64
 174  minutes_per_game                       15882 non-null  float64
 175  minutes_pct                            15882 non-null  float64
 176  games_starts.1                         15882 non-null  float64
 177  minutes_per_start                      15458 non-null  float64
 178  games_complete                         15882 non-null  float64
 179  games_subs                             15882 non-null  float64
 180  minutes_per_sub                        15733 non-null  float64
 181  unused_subs                            15882 non-null  float64
 182  points_per_game                        15881 non-null  float64
 183  on_goals_for                           15882 non-null  float64
 184  on_goals_against                       15882 non-null  float64
 185  plus_minus                             15882 non-null  float64
 186  plus_minus_per90                       15882 non-null  float64
 187  plus_minus_wow                         15879 non-null  float64
 188  on_xg_for                              15882 non-null  float64
 189  on_xg_against                          15882 non-null  float64
 190  xg_plus_minus                          15882 non-null  float64
 191  xg_plus_minus_per90                    15882 non-null  float64
 192  xg_plus_minus_wow                      15879 non-null  float64
dtypes: float64(185), object(8)
memory usage: 28.2+ MB

In [177]:
cols = list(df1.columns) + ["player_status"]

In [178]:
df_final_agg = df_final_agg[cols]

In [179]:
df_final_agg.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19184 entries, 0 to 19183
Data columns (total 193 columns):
 #    Column                                 Non-Null Count  Dtype
---   ------                                 --------------  -----
 0    player                                 19184 non-null  object
 1    nationality                            19176 non-null  object
 2    position                               19182 non-null  object
 3    age                                    19182 non-null  float64
 4    games                                  15882 non-null  float64
 5    games_starts                           15882 non-null  float64
 6    minutes                                15882 non-null  float64
 7    minutes_90s                            15882 non-null  float64
 8    goals                                  15882 non-null  float64
 9    assists                                15882 non-null  float64
 10   goals_assists                          15882 non-null  float64
 11   goals_pens                             15882 non-null  float64
 12   pens_made                              15882 non-null  float64
 13   pens_att                               15882 non-null  float64
 14   cards_yellow                           15882 non-null  float64
 15   cards_red                              15882 non-null  float64
 16   xg                                     15882 non-null  float64
 17   npxg                                   15882 non-null  float64
 18   xg_assist                              15882 non-null  float64
 19   npxg_xg_assist                         15882 non-null  float64
 20   progressive_carries                    15882 non-null  float64
 21   progressive_passes                     15882 non-null  float64
 22   progressive_passes_received            15882 non-null  float64
 23   goals_per90                            15882 non-null  float64
 24   assists_per90                          15882 non-null  float64
 25   goals_assists_per90                    15882 non-null  float64
 26   goals_pens_per90                       15882 non-null  float64
 27   goals_assists_pens_per90               15882 non-null  float64
 28   xg_per90                               15882 non-null  float64
 29   xg_assist_per90                        15882 non-null  float64
 30   xg_xg_assist_per90                     15882 non-null  float64
 31   npxg_per90                             15882 non-null  float64
 32   npxg_xg_assist_per90                   15882 non-null  float64
 33   gk_goals_against                       14454 non-null  float64
 34   gk_pens_allowed                        14454 non-null  float64
 35   gk_free_kick_goals_against             14454 non-null  float64
 36   gk_corner_kick_goals_against           14454 non-null  float64
 37   gk_own_goals_against                   14454 non-null  float64
 38   gk_psxg                                14454 non-null  float64
 39   gk_psnpxg_per_shot_on_target_against   14449 non-null  float64
 40   gk_psxg_net                            14454 non-null  float64
 41   gk_psxg_net_per90                      14454 non-null  float64
 42   gk_passes_completed_launched           14454 non-null  float64
 43   gk_passes_launched                     14454 non-null  float64
 44   gk_passes_pct_launched                 14451 non-null  float64
 45   gk_passes                              14454 non-null  float64
 46   gk_passes_throws                       14454 non-null  float64
 47   gk_pct_passes_launched                 14454 non-null  float64
 48   gk_passes_length_avg                   14454 non-null  float64
 49   gk_goal_kicks                          14454 non-null  float64
 50   gk_pct_goal_kicks_launched             14449 non-null  float64
 51   gk_goal_kick_length_avg                14449 non-null  float64
 52   gk_crosses                             14454 non-null  float64
 53   gk_crosses_stopped                     14454 non-null  float64
 54   gk_crosses_stopped_pct                 14449 non-null  float64
 55   gk_def_actions_outside_pen_area        14454 non-null  float64
 56   gk_def_actions_outside_pen_area_per90  14454 non-null  float64
 57   gk_avg_distance_def_actions            14444 non-null  float64
 58   goals.1                                15882 non-null  float64
 59   shots                                  15882 non-null  float64
 60   shots_on_target                        15882 non-null  float64
 61   shots_on_target_pct                    15394 non-null  float64
 62   shots_per90                            15882 non-null  float64
 63   shots_on_target_per90                  15882 non-null  float64
 64   goals_per_shot                         15394 non-null  float64
 65   goals_per_shot_on_target               15152 non-null  float64
 66   average_shot_distance                  15393 non-null  float64
 67   shots_free_kicks                       15882 non-null  float64
 68   pens_made.1                            15882 non-null  float64
 69   pens_att.1                             15882 non-null  float64
 70   xg.1                                   15882 non-null  float64
 71   npxg.1                                 15882 non-null  float64
 72   npxg_per_shot                          15393 non-null  float64
 73   xg_net                                 15882 non-null  float64
 74   npxg_net                               15882 non-null  float64
 75   passes_completed                       15882 non-null  float64
 76   passes                                 15882 non-null  float64
 77   passes_pct                             15850 non-null  float64
 78   passes_total_distance                  15882 non-null  float64
 79   passes_progressive_distance            15882 non-null  float64
 80   passes_completed_short                 15882 non-null  float64
 81   passes_short                           15882 non-null  float64
 82   passes_pct_short                       15823 non-null  float64
 83   passes_completed_medium                15882 non-null  float64
 84   passes_medium                          15882 non-null  float64
 85   passes_pct_medium                      15775 non-null  float64
 86   passes_completed_long                  15882 non-null  float64
 87   passes_long                            15882 non-null  float64
 88   passes_pct_long                        15658 non-null  float64
 89   assists.1                              15882 non-null  float64
 90   xg_assist.1                            15882 non-null  float64
 91   pass_xa                                15882 non-null  float64
 92   xg_assist_net                          15882 non-null  float64
 93   assisted_shots                         15882 non-null  float64
 94   passes_into_final_third                15882 non-null  float64
 95   passes_into_penalty_area               15882 non-null  float64
 96   crosses_into_penalty_area              15882 non-null  float64
 97   progressive_passes.1                   15882 non-null  float64
 98   passes.1                               15882 non-null  float64
 99   passes_live                            15882 non-null  float64
 100  passes_dead                            15882 non-null  float64
 101  passes_free_kicks                      15882 non-null  float64
 102  through_balls                          15882 non-null  float64
 103  passes_switches                        15882 non-null  float64
 104  crosses                                15882 non-null  float64
 105  throw_ins                              15882 non-null  float64
 106  corner_kicks                           15882 non-null  float64
 107  corner_kicks_in                        15882 non-null  float64
 108  corner_kicks_out                       15882 non-null  float64
 109  corner_kicks_straight                  15882 non-null  float64
 110  passes_completed.1                     15882 non-null  float64
 111  passes_offsides                        15882 non-null  float64
 112  passes_blocked                         15882 non-null  float64
 113  sca                                    15882 non-null  float64
 114  sca_per90                              15882 non-null  float64
 115  sca_passes_live                        15882 non-null  float64
 116  sca_passes_dead                        15882 non-null  float64
 117  sca_take_ons                           15882 non-null  float64
 118  sca_shots                              15882 non-null  float64
 119  sca_fouled                             15882 non-null  float64
 120  sca_defense                            15882 non-null  float64
 121  gca                                    15882 non-null  float64
 122  gca_per90                              15882 non-null  float64
 123  gca_passes_live                        15882 non-null  float64
 124  gca_passes_dead                        15882 non-null  float64
 125  gca_take_ons                           15882 non-null  float64
 126  gca_shots                              15882 non-null  float64
 127  gca_fouled                             15882 non-null  float64
 128  gca_defense                            15882 non-null  float64
 129  tackles                                15882 non-null  float64
 130  tackles_won                            15882 non-null  float64
 131  tackles_def_3rd                        15882 non-null  float64
 132  tackles_mid_3rd                        15882 non-null  float64
 133  tackles_att_3rd                        15882 non-null  float64
 134  challenge_tackles                      15882 non-null  float64
 135  challenges                             15882 non-null  float64
 136  challenge_tackles_pct                  15545 non-null  float64
 137  challenges_lost                        15882 non-null  float64
 138  blocks                                 15882 non-null  float64
 139  blocked_shots                          15882 non-null  float64
 140  blocked_passes                         15882 non-null  float64
 141  interceptions                          15882 non-null  float64
 142  tackles_interceptions                  15882 non-null  float64
 143  clearances                             15882 non-null  float64
 144  errors                                 15882 non-null  float64
 145  touches                                15882 non-null  float64
 146  touches_def_pen_area                   15882 non-null  float64
 147  touches_def_3rd                        15882 non-null  float64
 148  touches_mid_3rd                        15882 non-null  float64
 149  touches_att_3rd                        15882 non-null  float64
 150  touches_att_pen_area                   15882 non-null  float64
 151  touches_live_ball                      15882 non-null  float64
 152  take_ons                               15882 non-null  float64
 153  take_ons_won                           15882 non-null  float64
 154  take_ons_won_pct                       15466 non-null  float64
 155  take_ons_tackled                       15882 non-null  float64
 156  take_ons_tackled_pct                   15466 non-null  float64
 157  carries                                15882 non-null  float64
 158  carries_distance                       15882 non-null  float64
 159  carries_progressive_distance           15882 non-null  float64
 160  progressive_carries.1                  15882 non-null  float64
 161  carries_into_final_third               15882 non-null  float64
 162  carries_into_penalty_area              15882 non-null  float64
 163  miscontrols                            15882 non-null  float64
 164  dispossessed                           15882 non-null  float64
 165  passes_received                        15882 non-null  float64
 166  progressive_passes_received.1          15882 non-null  float64
 167  games.1                                15882 non-null  float64
 168  minutes.1                              15882 non-null  float64
 169  minutes_per_game                       15882 non-null  float64
 170  minutes_pct                            15882 non-null  float64
 171  games_starts.1                         15882 non-null  float64
 172  minutes_per_start                      15458 non-null  float64
 173  games_complete                         15882 non-null  float64
 174  games_subs                             15882 non-null  float64
 175  minutes_per_sub                        15733 non-null  float64
 176  unused_subs                            15882 non-null  float64
 177  points_per_game                        15881 non-null  float64
 178  on_goals_for                           15882 non-null  float64
 179  on_goals_against                       15882 non-null  float64
 180  plus_minus                             15882 non-null  float64
 181  plus_minus_per90                       15882 non-null  float64
 182  plus_minus_wow                         15879 non-null  float64
 183  on_xg_for                              15882 non-null  float64
 184  on_xg_against                          15882 non-null  float64
 185  xg_plus_minus                          15882 non-null  float64
 186  xg_plus_minus_per90                    15882 non-null  float64
 187  xg_plus_minus_wow                      15879 non-null  float64
 188  Team                                   19184 non-null  object
 189  League                                 19184 non-null  object
 190  Team_Logo                              19184 non-null  object
 191  Season                                 19184 non-null  object
 192  player_status                          19184 non-null  object
dtypes: float64(185), object(8)
memory usage: 28.2+ MB

In [180]:
df_final_agg.to_csv("data/all_players_plus_historic_data.csv")

In [181]:
df_final_agg[df_final_agg.Team == "Real Madrid"]

,player,nationality,position,age,games,games_starts,minutes,minutes_90s,goals,assists,...,on_xg_for,on_xg_against,xg_plus_minus,xg_plus_minus_per90,xg_plus_minus_wow,Team,League,Team_Logo,Season,player_status
1086,Altube,ESP,GK,20.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2020-21,retired or inactive
1379,Andriy Lunin,UKR,GK,25.0,9.250000,9.250000,832.500000,9.250000,0.000000,0.250000,...,17.425000,9.750000,7.700000,0.407500,-0.442500,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
1629,Antonio Rüdiger,GER,DF,31.0,29.600000,27.000000,2432.000000,27.020000,1.200000,0.000000,...,48.200000,24.400000,23.760000,0.886000,0.104000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
1683,Arda Güler,TUR,MF,19.0,19.000000,9.000000,813.500000,9.050000,4.500000,2.000000,...,17.600000,10.400000,7.200000,0.705000,-0.175000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
1876,Aurélien Tchouaméni,FRA,DF,24.0,32.600000,29.200000,2557.400000,28.400000,1.600000,2.200000,...,49.860000,28.760000,21.120000,0.762000,-0.300000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
2373,Brahim Díaz,MAR,FW,24.0,30.500000,19.000000,1520.750000,16.900000,5.500000,4.500000,...,32.675000,16.275000,16.425000,1.002500,0.520000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
2918,Chema,ESP,MF,19.0,6.500000,4.250000,370.750000,4.125000,0.250000,0.000000,...,1.325000,1.800000,-0.475000,-0.130000,-0.250000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
3446,Dani Carvajal,ESP,DF,32.0,20.000000,16.000000,1413.000000,15.700000,1.200000,2.000000,...,28.980000,14.800000,14.160000,0.878000,0.128000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
3447,Dani Ceballos,ESP,MF,27.0,21.800000,11.600000,1053.600000,11.700000,0.000000,1.800000,...,21.100000,12.240000,8.860000,0.822000,0.122000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
3601,Daniel Yáñez,ESP,FW,17.0,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,-0.860000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
3735,David Alaba,AUT,DF,32.0,21.200000,19.800000,1725.200000,19.160000,1.000000,2.200000,...,37.580000,21.500000,16.080000,0.828000,-0.340000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
3776,David Jiménez,ESP,DF,20.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
4080,Diego Aguado,ESP,DF,17.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
4146,Diego Piñeiro,ESP,GK,19.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2023-24,retired or inactive
4495,Eden Hazard,BEL,FW,31.0,12.666667,5.333333,481.666667,5.366667,1.000000,1.333333,...,7.933333,5.433333,2.466667,0.610000,-0.206667,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2022-23,retired or inactive
4509,Edgar Pujol,DOM,DF,18.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2023-24,retired or inactive
4565,Eduardo Camavinga,FRA,MF,21.0,25.333333,15.833333,1451.666667,16.116667,0.666667,1.333333,...,28.050000,17.033333,11.000000,0.378333,-0.305000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
4869,Endrick,BRA,FW,18.0,22.000000,3.000000,363.000000,4.000000,1.000000,0.000000,...,8.600000,4.200000,4.400000,1.080000,0.250000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
5377,Federico Valverde,URU,MF,26.0,32.400000,26.000000,2320.200000,25.800000,3.600000,3.400000,...,49.000000,26.080000,22.900000,0.864000,0.286000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
5438,Ferland Mendy,FRA,DF,29.0,20.600000,18.800000,1603.600000,17.820000,0.600000,0.600000,...,31.380000,17.720000,13.660000,0.696000,-0.070000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
5653,Fran,ESP,GK,19.0,1.000000,1.000000,90.000000,1.000000,0.000000,0.000000,...,3.400000,0.800000,2.700000,2.660000,1.860000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
5656,Fran Garcia,ESP,DF,24.0,32.000000,27.750000,2500.250000,27.775000,1.000000,2.500000,...,40.350000,33.875000,6.475000,0.367500,-0.567500,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
5657,Fran González,ESP,DF,24.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2023-24,retired or inactive
6038,Gareth Bale,WAL,FW,32.0,12.500000,7.000000,600.000000,6.650000,6.000000,1.000000,...,9.900000,6.350000,3.550000,0.410000,0.070000,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2021-22,retired or inactive
6392,Gonzalo García,ESP,FW,20.0,2.500000,0.000000,37.500000,0.400000,0.000000,0.500000,...,1.300000,0.200000,1.050000,1.635000,0.780000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
7609,Jacobo Ramón,ESP,DF,19.0,3.000000,2.000000,204.000000,2.300000,1.000000,0.000000,...,5.100000,2.500000,2.700000,1.180000,0.340000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
8201,Jesús Vallejo,ESP,DF,27.0,6.800000,4.200000,391.400000,4.340000,0.000000,0.200000,...,5.900000,7.100000,-1.220000,0.726000,0.382000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
8729,Joselu,ESP,FW,33.0,35.500000,29.250000,2706.250000,30.050000,12.750000,2.750000,...,38.825000,40.975000,-2.175000,0.062500,0.487500,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2023-24,retired or inactive
9131,Jude Bellingham,ENG,MF,21.0,30.200000,27.400000,2396.200000,26.620000,8.000000,5.800000,...,51.500000,31.520000,19.940000,0.766000,-0.096000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
10090,Kylian Mbappé,FRA,FW,25.0,32.600000,30.200000,2657.200000,29.520000,28.400000,7.800000,...,63.400000,33.560000,29.820000,1.014000,0.584000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
10631,Lorenzo Aguado,ESP,DF,21.0,2.000000,0.000000,5.000000,0.100000,0.000000,0.000000,...,0.200000,0.000000,0.200000,3.530000,2.670000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
10946,Lucas Vázquez,ESP,DF,33.0,27.400000,18.400000,1686.600000,18.740000,2.600000,3.400000,...,35.460000,21.440000,13.980000,0.796000,-0.102000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
11107,Luka Modrić,CRO,MF,38.0,32.600000,22.200000,2004.800000,22.300000,3.000000,5.200000,...,39.640000,23.140000,16.500000,0.766000,-0.158000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
11750,Mario Rivas,ESP,DF,17.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
11760,Mario de Luis,ESP,GK,21.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2023-24,retired or inactive
15126,Raúl Asencio,ESP,DF,21.0,23.000000,18.000000,1670.000000,18.600000,0.000000,1.000000,...,40.200000,20.600000,19.700000,1.060000,0.400000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
15543,Rodrygo,BRA,FW,23.0,30.600000,20.400000,1838.600000,20.400000,6.000000,5.600000,...,38.820000,20.860000,17.980000,0.874000,0.108000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
16379,Sergio Mestre,ESP,GK,19.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
16394,Sergio Santos,ESP,DF,20.0,1.000000,0.000000,11.000000,0.100000,0.000000,0.000000,...,0.500000,0.300000,0.200000,1.450000,0.720000,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2021-22,retired or inactive
17215,Thibaut Courtois,BEL,GK,32.0,27.800000,27.800000,2496.400000,27.740000,0.000000,0.000000,...,51.380000,29.200000,22.180000,0.834000,0.437500,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
17669,Toni Kroos,GER,MF,33.0,29.750000,24.500000,2124.750000,23.600000,1.750000,6.250000,...,40.525000,25.100000,15.475000,0.652500,-0.385000,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2023-24,retired or inactive
18007,Victor Valdepeñas,ESP,DF,17.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
18062,Vinicius Júnior,BRA,FW,24.0,31.800000,26.000000,2319.800000,25.780000,11.200000,7.000000,...,46.540000,26.580000,19.980000,0.770000,-0.162000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
18067,Vinicius Tobias,BRA,DF,19.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202509241/tlogo/fb/5...,2023-24,retired or inactive
18179,Víctor Muñoz,ESP,FW,21.0,2.000000,0.000000,36.000000,0.400000,0.000000,0.000000,...,1.800000,0.600000,1.200000,3.070000,2.240000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
18711,Youssef Lekhedim,ESP,DF,18.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active
19078,Éder Militão,BRA,DF,26.0,20.600000,18.800000,1660.200000,18.440000,1.600000,0.600000,...,33.400000,20.060000,13.320000,0.668000,-0.332000,Real Madrid,La Liga,https://cdn.ssref.net/req/202507021/tlogo/fb/5...,2024-25,active